"""
We will be designating a scoring system based on inversions to compare and
score the steps generated by the large language model and the actual algorithm.
"""
import numpy as np
import math


def give_rank_sorted_array(arr):
    sort_dict = dict(zip(sorted(list(set(arr))), np.arange(1, len(arr) + 1).tolist()))
    sorted_arr = [sort_dict[i] for i in arr]

    return sorted_arr


def kendall_tau_inversion(ground_truth, llm_output):
    """
    Returns the number of inversions Inv(π, σ)
    π : ranking induced by ground truth
    σ : ranking induced by LLM output
    We define inversion in this case as a pair of nodes (i, j) such that
    di < dj but di'>dj' where
    di denotes distances in ground truth distance array
    di' denotes distances in llm generated distance array
    normalised kendal tau distance = 1-inv(π,σ)
                                    --------
                                     (  n  )
                                        2
    we ignore if di=di' or di = infinity or di' = infinity
    """
    if len(llm_output) != len(ground_truth):
        return 0, []
    elif llm_output == ground_truth:
        return 1, []
    ground_truth_rank_sorted = give_rank_sorted_array(ground_truth)
    llm_output_rank_sorted = give_rank_sorted_array(llm_output)
    n = len(ground_truth_rank_sorted)
    inv = 0
    inv_set = []

    for i in range(n):
        for j in range(i + 1, n):

            ''' how to deal with infinity'''
            if math.isinf(ground_truth_rank_sorted[i]) or math.isinf(ground_truth_rank_sorted[j]):
                continue

            # di = di'
            if ground_truth_rank_sorted[i] == ground_truth_rank_sorted[j]:
                continue

            # if di>dj but di'<dj'
            if ground_truth_rank_sorted[i] < ground_truth_rank_sorted[j]:
                if llm_output_rank_sorted[i] > llm_output_rank_sorted[j]:
                    inv += 1
                    inv_set.append((i, j))
            # if di < dj but di'>dj'
            else:
                if llm_output_rank_sorted[j] > llm_output_rank_sorted[i]:
                    inv += 1
    normalised_kendall_tau_dist = 1 - inv / (math.comb(n, 2))

    return normalised_kendall_tau_dist, inv_set


def weighted_inversion(llm_output, ground_truth, inv_set, inv_score):
    """
    This function gives a weighted inversion between two arrays because
    in kendal tau inversion the penalty for swapping 1 with 2 is same as 2 with 100
    but the penalty should also reflect the size of the error as well

    Weighted inversion distance generalizes Kendall Tau by scaling each ordering
    violation by the ground-truth distance gap between nodes, thereby penalizing
    severe shortest-path mis-orderings more heavily than minor ones.

    I={}
    """
    if not inv_set:
        if inv_score == 1:
            return 1
        else:
            return 0
    n = len(ground_truth)
    if len(llm_output) != len(ground_truth):
        return 0
    elif llm_output == ground_truth:
        return 1

    weight = 0
    for (i, j) in inv_set:
        weight += abs(ground_truth[i] - ground_truth[j])
    weight_max = 0
    for i in range(n):
        for j in range(i + 1, n):
            if math.isinf(ground_truth[i]) or math.isinf(ground_truth[j]):
                continue
            if ground_truth[i] == ground_truth[j]:
                continue
            weight_max += abs(ground_truth[i] - ground_truth[j])

    weighted_inversion_dist = 1 - weight / weight_max
    return weighted_inversion_dist


def inversion_score(llm_output, ground_truth):
    """
    Gives the score between the llm generate distance array and the
    actual array for every step in the algorithm
    """
    basic_inversion_dist, inversion_set = kendall_tau_inversion(llm_output, ground_truth)
    weighted_inversion_dist = weighted_inversion(llm_output, ground_truth, inversion_set, basic_inversion_dist)

    a = 0.5
    return a * basic_inversion_dist + (1 - a) * weighted_inversion_dist
